/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package icbloodlog;

import java.awt.Color;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.util.HashMap;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author JohnS
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        SetIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Apos = new javax.swing.JTextField();
        Bneg = new javax.swing.JTextField();
        Oneg = new javax.swing.JTextField();
        Opos = new javax.swing.JTextField();
        ABneg = new javax.swing.JTextField();
        Aneg = new javax.swing.JTextField();
        Bpos = new javax.swing.JTextField();
        ABpos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blood Logistics Manager");
        setBackground(new java.awt.Color(102, 102, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 102, 102));
        setIconImage(getIconImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel1.setText("A Positive");

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel2.setText("B Positive");

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel3.setText("A Negative");

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel4.setText("B Negative");

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel5.setText("O Negative");

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel6.setText("AB Positive");

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel7.setText("AB Negative");

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel8.setText("O Positive");

        jButton1.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendPintNumber(evt);
            }
        });

        Apos.setBackground(new java.awt.Color(255, 204, 204));
        Apos.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        Apos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Bneg.setBackground(new java.awt.Color(255, 204, 204));
        Bneg.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        Bneg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Oneg.setBackground(new java.awt.Color(255, 204, 204));
        Oneg.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        Oneg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Opos.setBackground(new java.awt.Color(255, 204, 204));
        Opos.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        Opos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ABneg.setBackground(new java.awt.Color(255, 204, 204));
        ABneg.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        ABneg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Aneg.setBackground(new java.awt.Color(255, 204, 204));
        Aneg.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        Aneg.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Bpos.setBackground(new java.awt.Color(255, 204, 204));
        Bpos.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        Bpos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ABpos.setBackground(new java.awt.Color(255, 204, 204));
        ABpos.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        ABpos.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel9.setText("Number of Pints");

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel10.setText("Blood Types");

        jLabel11.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel11.setText("Set City and State");

        jLabel12.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel12.setText("City");

        jLabel13.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jLabel13.setText("State");

        jTextField9.setBackground(new java.awt.Color(255, 204, 204));
        jTextField9.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField10.setBackground(new java.awt.Color(255, 204, 204));
        jTextField10.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel14.setText("Set Radius From Location to Search");

        jComboBox1.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 Miles", "20 Miles", "50 Miles", "100 Miles", "200 Miles", "500 Miles", "Unlimited Miles" }));

        jButton3.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jButton3.setText("Submit");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setRadiusAway(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel15.setText("Set Number of Injured");

        jTextField11.setBackground(new java.awt.Color(255, 204, 204));
        jTextField11.setFont(new java.awt.Font("Corbel", 0, 16)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton4.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jButton4.setText("Submit");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setInjuryNumber(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(jLabel11))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel14)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField9))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(Apos)
                            .addComponent(Oneg)
                            .addComponent(Opos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ABneg)
                            .addComponent(Aneg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bpos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bneg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ABpos, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel9)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aneg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bpos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bneg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ABpos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ABneg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Opos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Oneg, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        Apos.getAccessibleContext().setAccessibleName("");
        Opos.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("Blood Logistics Manager");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setInjuryNumber(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setInjuryNumber
        // TODO add your handling code here:
    }//GEN-LAST:event_setInjuryNumber

    private void setRadiusAway(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRadiusAway
        // TODO add your handling code here:
        MapRequest mr = new MapRequest();
        
        String cityOut = jTextField10.getText();
        String stateOut = jTextField9.getText();
        
        try {
            String hospitals = mr.findHospital(cityOut, stateOut);
        } catch (Exception ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ResponseWindow rw = new ResponseWindow();
        
        rw.jLabel1.setText("   000   ");
        
        //rw.setVisible(true);
              
        //int number = 0;

        //Scanner scan = new Scanner(System.in);
        //scan.useDelimiter(" ");

        HashMap<String, Integer> blood = new HashMap<String, Integer>();

        /*
        System.out.println("How many types of blood do you need?");
        number = Integer.parseInt(scan.nextLine());
        System.out.println("What type of blood and how much (in pints) do you need? (Put a space between type and pints)");
        */
        //String input = scan.nextLine();
        //String[] bloodType = new String[number * 2];
        /*
        String response = scan.nextLine();
        String[] record = response.split(" ");

        for (int i = 0; i + 1 < record.length; i = i + 2) {
           blood.put(record[i], Integer.parseInt(record[i + 1]));
        }

        double x, y = 0;
        System.out.print("Please input your current location (x coordinate): ");
        */
        int x = 200;
        //System.out.print("Please input your current location (y coordinate): ");
        int y = 200;
        //*/
        
        DecimalFormat df = new DecimalFormat("#0.0#");

        Hospital[] check = new Hospital[3]; // number of hospitals in range, initiatilzed at 0 for placeholder.
        check[0] = new Hospital("East Alabama Health Center", 100, 200);
        check[1] = new Hospital("Jackson Hospital", 200, 400);
        check[2] = new Hospital("Auburn Medical Park", 20, 30);
        check[0].setHash("AB+", 2);
        check[1].setHash("AB+", 5);
        check[2].setHash("AB+", 8);
        check[0].setHash("A+", 12);
        check[1].setHash("A+", 40);
        check[2].setHash("A+", 34);
        check[0].setHash("A-", 21);
        check[1].setHash("A-", 12);
        check[2].setHash("A-", 17);
        check[0].setHash("B+", 24);
        check[1].setHash("B+", 58);
        check[2].setHash("B+", 9);
        check[0].setHash("B-", 17);
        check[1].setHash("B-", 9);
        check[2].setHash("B-", 70);
        check[0].setHash("AB+", 0);
        check[1].setHash("AB+", 31);
        check[2].setHash("AB+", 4);
        check[0].setHash("AB-", 19);
        check[1].setHash("AB-", 23);
        check[2].setHash("AB-", 31);
        check[0].setHash("O-", 18);
        check[1].setHash("O-", 20);
        check[2].setHash("O-", 33);
        check[0].setHash("O+", 17);
        check[1].setHash("O+", 24);
        check[2].setHash("O+", 7);
        
        rw.jLabel1.setText(check[0].getName());
        rw.jLabel2.setText(check[1].getName());
        rw.jLabel3.setText(check[2].getName());
        
        int apos = Integer.parseInt(Apos.getText());
        int aneg = Integer.parseInt(Aneg.getText());
        int bpos = Integer.parseInt(Bpos.getText());
        int bneg = Integer.parseInt(Bneg.getText());
        int abpos = Integer.parseInt(ABpos.getText());
        int abneg = Integer.parseInt(ABneg.getText());
        int opos = Integer.parseInt(Opos.getText());
        int oneg = Integer.parseInt(Oneg.getText());
        
        double pintsSum = apos + aneg + bpos + bneg + abpos + abneg + opos + oneg;
        
        double apospcent = apos / pintsSum;
        double anegpcent = aneg / pintsSum;
        double bpospcent = bpos / pintsSum;
        double bnegpcent = bneg / pintsSum;
        double abpospcent = abpos / pintsSum;
        double abnegpcent = abneg / pintsSum;
        double opospcent = opos / pintsSum;
        double onegpcent = oneg / pintsSum;
        
        double totalpcent = apospcent + anegpcent + bpospcent + bnegpcent + abpospcent + abnegpcent + opospcent + onegpcent;
        
        double totalPercentH1 = (check[0].getBlood().get("A+") 
                + (check[0].getBlood().get("A-"))
                +(check[0].getBlood().get("B+"))
                +(check[0].getBlood().get("B-"))
                +(check[0].getBlood().get("AB+"))
                +(check[0].getBlood().get("AB-"))
                +(check[0].getBlood().get("O+"))
                +(check[0].getBlood().get("O-")));
        
        double H1out = (totalPercentH1 / pintsSum)*100;
        
        double totalPercentH2 = (check[1].getBlood().get("A+") 
                + (check[1].getBlood().get("A-"))
                +(check[1].getBlood().get("B+"))
                +(check[1].getBlood().get("B-"))
                +(check[1].getBlood().get("AB+"))
                +(check[1].getBlood().get("AB-"))
                +(check[1].getBlood().get("O+"))
                +(check[1].getBlood().get("O-")));
        
        double H2out = (totalPercentH2 / pintsSum)*100;
        
        double totalPercentH3 = ((check[2].getBlood().get("A+")) 
                + (check[2].getBlood().get("A-"))
                +(check[2].getBlood().get("B+"))
                +(check[2].getBlood().get("B-"))
                +(check[2].getBlood().get("AB+"))
                +(check[2].getBlood().get("AB-"))
                +(check[2].getBlood().get("O+"))
                +(check[2].getBlood().get("O-")));
        
        double H3out = (totalPercentH3 / pintsSum)*100;
        
        rw.hosp1.setText(H1out + "% " + "Match to Need");
        rw.hosp2.setText(H2out + "% " + "Match to Need");
        rw.hosp3.setText(H3out + "% " + "Match to Need");
        rw.setVisible(true);
        /*
        try {
           for (int j = 0; j + 1 < record.length; j = j + 2) {
              for (int i = 1; i < check.length; i++) {
                 if (check[i - 1].getBlood().get(record[j]) < check[i].getBlood().get(record[j]) && check[i].getBlood().get(record[j]) >= blood.get(record[j]) ) {
                    System.out.println("Hospital " + check[i].getName() + " has the required amount to fulfill your request."); 
                    System.out.println("Hospital " + check[i].getName() + " is " + df.format(Math.sqrt(Math.pow((check[i].getY() - y), 2) + Math.pow((check[i].getX() - x), 2))) + " miles away.\n");  
                 }
                 else {
                    System.out.println("Hospital " + check[i].getName() + " cannot fulfill request.");
                 }
              }
           }
        }
        catch (NullPointerException e) {
           System.out.println("No blood could be found in the given area! ERROR! ERROR!");
        }
        */
        
    }//GEN-LAST:event_setRadiusAway

    
    
    
    
    private void sendPintNumber(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendPintNumber
        // TODO add your handling code here:
    }//GEN-LAST:event_sendPintNumber

    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("frameIcon.png")));
        getContentPane().setBackground(new java.awt.Color(150, 141, 244));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ABneg;
    public javax.swing.JTextField ABpos;
    public javax.swing.JTextField Aneg;
    public javax.swing.JTextField Apos;
    public javax.swing.JTextField Bneg;
    public javax.swing.JTextField Bpos;
    public javax.swing.JTextField Oneg;
    public javax.swing.JTextField Opos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
